name: spikeflownet
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37he30daa8_1
  - cudatoolkit=10.0.130=0
  - freetype=2.10.2=h5ab3b9f_0
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - pycparser=2.20=py_0
  - python=3.7.7=hcff3b4d_5
  - pytorch=1.1.0=py3.7_cuda10.0.130_cudnn7.5.1_0
  - readline=8.0=h7b6447c_0
  - setuptools=47.3.1=py37_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.3.0=py37_cu10.0.130_1
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - h5py==2.10.0
    - opencv-python==4.2.0.32
    - protobuf==3.12.2
    - tensorboardx==2.1
prefix: /home/adarsh/anaconda3/envs/spikeflownet

